DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?authenticityType a <http://mu.semte.ch/vocabularies/ext/AuthenticityType>.
    ?authenticityType ?authenticityTypeP ?authenticityTypeO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?authenticityType a <http://mu.semte.ch/vocabularies/ext/AuthenticityType>.
    ?authenticityType ?authenticityTypeP ?authenticityTypeO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?authenticityType a <http://mu.semte.ch/vocabularies/ext/AuthenticityType>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?authenticityType a <http://mu.semte.ch/vocabularies/ext/AuthenticityType>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?authenticityType ?authenticityTypeP ?authenticityTypeO.
  }
}