DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?job a <http://vocab.deri.ie/cogs#Job>.
    ?job ?jobP ?jobO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?job a <http://vocab.deri.ie/cogs#Job>.
    ?job ?jobP ?jobO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?job a <http://vocab.deri.ie/cogs#Job>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?job a <http://vocab.deri.ie/cogs#Job>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?job ?jobP ?jobO.
  }
}