DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?periodOfTime a <http://data.europa.eu/m8g/PeriodOfTime>.
    ?periodOfTime ?periodOfTimeP ?periodOfTimeO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?periodOfTime a <http://data.europa.eu/m8g/PeriodOfTime>.
    ?periodOfTime ?periodOfTimeP ?periodOfTimeO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?periodOfTime a <http://data.europa.eu/m8g/PeriodOfTime>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?periodOfTime a <http://data.europa.eu/m8g/PeriodOfTime>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?periodOfTime ?periodOfTimeP ?periodOfTimeO.
  }
}