DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?identifier a <http://www.w3.org/ns/adms#Identifier>.
    ?identifier ?identifierP ?identifierO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?identifier a <http://www.w3.org/ns/adms#Identifier>.
    ?identifier ?identifierP ?identifierO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?identifier a <http://www.w3.org/ns/adms#Identifier>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?identifier a <http://www.w3.org/ns/adms#Identifier>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?identifier ?identifierP ?identifierO.
  }
}