DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?marCode a <http://dev.lynx.lblod.info/vocabulary#MARCode>.
    ?marCode ?marCodeP ?marCodeO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?marCode a <http://dev.lynx.lblod.info/vocabulary#MARCode>.
    ?marCode ?marCodeP ?marCodeO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?marCode a <http://dev.lynx.lblod.info/vocabulary#MARCode>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?marCode a <http://dev.lynx.lblod.info/vocabulary#MARCode>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?marCode ?marCodeP ?marCodeO.
  }
}