DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?task a <http://redpencil.data.gift/vocabularies/tasks/Task>.
    ?task ?taskP ?taskO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?task a <http://redpencil.data.gift/vocabularies/tasks/Task>.
    ?task ?taskP ?taskO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?task a <http://redpencil.data.gift/vocabularies/tasks/Task>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?task a <http://redpencil.data.gift/vocabularies/tasks/Task>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?task ?taskP ?taskO.
  }
}