DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?4f63ded4d168 a <http://data.lblod.info/ML2GrowClassification/e25aa915-c026-4529-9137-4f63ded4d168>.
    ?4f63ded4d168 ?4f63ded4d168P ?4f63ded4d168O.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?4f63ded4d168 a <http://data.lblod.info/ML2GrowClassification/e25aa915-c026-4529-9137-4f63ded4d168>.
    ?4f63ded4d168 ?4f63ded4d168P ?4f63ded4d168O.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?4f63ded4d168 a <http://data.lblod.info/ML2GrowClassification/e25aa915-c026-4529-9137-4f63ded4d168>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?4f63ded4d168 a <http://data.lblod.info/ML2GrowClassification/e25aa915-c026-4529-9137-4f63ded4d168>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?4f63ded4d168 ?4f63ded4d168P ?4f63ded4d168O.
  }
}