DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    ?bestuurseenheid ?bestuurseenheidP ?bestuurseenheidO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    ?bestuurseenheid ?bestuurseenheidP ?bestuurseenheidO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?bestuurseenheid ?bestuurseenheidP ?bestuurseenheidO.
  }
}