DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?e0fa29427f13 a <http://data.lblod.info/ML2GrowClassification/b06c09cc-71ad-41a5-a942-e0fa29427f13>.
    ?e0fa29427f13 ?e0fa29427f13P ?e0fa29427f13O.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?e0fa29427f13 a <http://data.lblod.info/ML2GrowClassification/b06c09cc-71ad-41a5-a942-e0fa29427f13>.
    ?e0fa29427f13 ?e0fa29427f13P ?e0fa29427f13O.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?e0fa29427f13 a <http://data.lblod.info/ML2GrowClassification/b06c09cc-71ad-41a5-a942-e0fa29427f13>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?e0fa29427f13 a <http://data.lblod.info/ML2GrowClassification/b06c09cc-71ad-41a5-a942-e0fa29427f13>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?e0fa29427f13 ?e0fa29427f13P ?e0fa29427f13O.
  }
}