DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?dataContainer a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer>.
    ?dataContainer ?dataContainerP ?dataContainerO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?dataContainer a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer>.
    ?dataContainer ?dataContainerP ?dataContainerO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?dataContainer a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?dataContainer a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?dataContainer ?dataContainerP ?dataContainerO.
  }
}