DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?onlineAccount a <http://xmlns.com/foaf/0.1/OnlineAccount>.
    ?onlineAccount ?onlineAccountP ?onlineAccountO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?onlineAccount a <http://xmlns.com/foaf/0.1/OnlineAccount>.
    ?onlineAccount ?onlineAccountP ?onlineAccountO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?onlineAccount a <http://xmlns.com/foaf/0.1/OnlineAccount>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?onlineAccount a <http://xmlns.com/foaf/0.1/OnlineAccount>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?onlineAccount ?onlineAccountP ?onlineAccountO.
  }
}