DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?69fa7020fc85 a <http://data.lblod.info/ML2GrowClassification/b595897a-3a3e-406e-840d-69fa7020fc85>.
    ?69fa7020fc85 ?69fa7020fc85P ?69fa7020fc85O.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?69fa7020fc85 a <http://data.lblod.info/ML2GrowClassification/b595897a-3a3e-406e-840d-69fa7020fc85>.
    ?69fa7020fc85 ?69fa7020fc85P ?69fa7020fc85O.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?69fa7020fc85 a <http://data.lblod.info/ML2GrowClassification/b595897a-3a3e-406e-840d-69fa7020fc85>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?69fa7020fc85 a <http://data.lblod.info/ML2GrowClassification/b595897a-3a3e-406e-840d-69fa7020fc85>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?69fa7020fc85 ?69fa7020fc85P ?69fa7020fc85O.
  }
}