DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?entry a <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#Entry>.
    ?entry ?entryP ?entryO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?entry a <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#Entry>.
    ?entry ?entryP ?entryO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?entry a <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#Entry>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?entry a <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#Entry>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?entry ?entryP ?entryO.
  }
}