DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?eec3f15bd09b a <http://data.lblod.info/ML2GrowClassification/a4aed4e7-7a70-4481-a374-eec3f15bd09b>.
    ?eec3f15bd09b ?eec3f15bd09bP ?eec3f15bd09bO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?eec3f15bd09b a <http://data.lblod.info/ML2GrowClassification/a4aed4e7-7a70-4481-a374-eec3f15bd09b>.
    ?eec3f15bd09b ?eec3f15bd09bP ?eec3f15bd09bO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?eec3f15bd09b a <http://data.lblod.info/ML2GrowClassification/a4aed4e7-7a70-4481-a374-eec3f15bd09b>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?eec3f15bd09b a <http://data.lblod.info/ML2GrowClassification/a4aed4e7-7a70-4481-a374-eec3f15bd09b>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?eec3f15bd09b ?eec3f15bd09bP ?eec3f15bd09bO.
  }
}