DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?b4d7c0bf4e13 a <http://data.lblod.info/ML2GrowClassification/87adadcd-b5ef-4c89-9ca8-b4d7c0bf4e13>.
    ?b4d7c0bf4e13 ?b4d7c0bf4e13P ?b4d7c0bf4e13O.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?b4d7c0bf4e13 a <http://data.lblod.info/ML2GrowClassification/87adadcd-b5ef-4c89-9ca8-b4d7c0bf4e13>.
    ?b4d7c0bf4e13 ?b4d7c0bf4e13P ?b4d7c0bf4e13O.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?b4d7c0bf4e13 a <http://data.lblod.info/ML2GrowClassification/87adadcd-b5ef-4c89-9ca8-b4d7c0bf4e13>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?b4d7c0bf4e13 a <http://data.lblod.info/ML2GrowClassification/87adadcd-b5ef-4c89-9ca8-b4d7c0bf4e13>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?b4d7c0bf4e13 ?b4d7c0bf4e13P ?b4d7c0bf4e13O.
  }
}