DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?taxCategory a <http://dev.lynx.lblod.info/vocabulary#TaxCategory>.
    ?taxCategory ?taxCategoryP ?taxCategoryO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?taxCategory a <http://dev.lynx.lblod.info/vocabulary#TaxCategory>.
    ?taxCategory ?taxCategoryP ?taxCategoryO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?taxCategory a <http://dev.lynx.lblod.info/vocabulary#TaxCategory>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?taxCategory a <http://dev.lynx.lblod.info/vocabulary#TaxCategory>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?taxCategory ?taxCategoryP ?taxCategoryO.
  }
}