DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?taxReport a <http://dev.lynx.lblod.info/vocabulary#TaxReport>.
    ?taxReport ?taxReportP ?taxReportO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?taxReport a <http://dev.lynx.lblod.info/vocabulary#TaxReport>.
    ?taxReport ?taxReportP ?taxReportO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?taxReport a <http://dev.lynx.lblod.info/vocabulary#TaxReport>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?taxReport a <http://dev.lynx.lblod.info/vocabulary#TaxReport>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?taxReport ?taxReportP ?taxReportO.
  }
}