DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?bestuurseenheidClassificatieCode a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    ?bestuurseenheidClassificatieCode ?bestuurseenheidClassificatieCodeP ?bestuurseenheidClassificatieCodeO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheidClassificatieCode a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    ?bestuurseenheidClassificatieCode ?bestuurseenheidClassificatieCodeP ?bestuurseenheidClassificatieCodeO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?bestuurseenheidClassificatieCode a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?bestuurseenheidClassificatieCode a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?bestuurseenheidClassificatieCode ?bestuurseenheidClassificatieCodeP ?bestuurseenheidClassificatieCodeO.
  }
}