DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?a6a31f72333e a <http://data.lblod.info/ML2GrowClassification/5c616d64-fe79-4eb3-a024-a6a31f72333e>.
    ?a6a31f72333e ?a6a31f72333eP ?a6a31f72333eO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?a6a31f72333e a <http://data.lblod.info/ML2GrowClassification/5c616d64-fe79-4eb3-a024-a6a31f72333e>.
    ?a6a31f72333e ?a6a31f72333eP ?a6a31f72333eO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?a6a31f72333e a <http://data.lblod.info/ML2GrowClassification/5c616d64-fe79-4eb3-a024-a6a31f72333e>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?a6a31f72333e a <http://data.lblod.info/ML2GrowClassification/5c616d64-fe79-4eb3-a024-a6a31f72333e>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?a6a31f72333e ?a6a31f72333eP ?a6a31f72333eO.
  }
}