DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?bestuursorgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    ?bestuursorgaan ?bestuursorgaanP ?bestuursorgaanO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuursorgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    ?bestuursorgaan ?bestuursorgaanP ?bestuursorgaanO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?bestuursorgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?bestuursorgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?bestuursorgaan ?bestuursorgaanP ?bestuursorgaanO.
  }
}