DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?concept a <http://www.w3.org/2004/02/skos/core#Concept>.
    ?concept ?conceptP ?conceptO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?concept a <http://www.w3.org/2004/02/skos/core#Concept>.
    ?concept ?conceptP ?conceptO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?concept a <http://www.w3.org/2004/02/skos/core#Concept>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?concept a <http://www.w3.org/2004/02/skos/core#Concept>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?concept ?conceptP ?conceptO.
  }
}