DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?c6caf7e9848a a <http://data.lblod.info/ML2GrowClassification/f60a87e6-f262-470e-9c23-c6caf7e9848a>.
    ?c6caf7e9848a ?c6caf7e9848aP ?c6caf7e9848aO.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?c6caf7e9848a a <http://data.lblod.info/ML2GrowClassification/f60a87e6-f262-470e-9c23-c6caf7e9848a>.
    ?c6caf7e9848a ?c6caf7e9848aP ?c6caf7e9848aO.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?c6caf7e9848a a <http://data.lblod.info/ML2GrowClassification/f60a87e6-f262-470e-9c23-c6caf7e9848a>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?c6caf7e9848a a <http://data.lblod.info/ML2GrowClassification/f60a87e6-f262-470e-9c23-c6caf7e9848a>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?c6caf7e9848a ?c6caf7e9848aP ?c6caf7e9848aO.
  }
}