DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?4dc8a089e387 a <http://data.lblod.info/ML2GrowClassification/c7776fbb-a32a-419c-b996-4dc8a089e387>.
    ?4dc8a089e387 ?4dc8a089e387P ?4dc8a089e387O.
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?4dc8a089e387 a <http://data.lblod.info/ML2GrowClassification/c7776fbb-a32a-419c-b996-4dc8a089e387>.
    ?4dc8a089e387 ?4dc8a089e387P ?4dc8a089e387O.
  }
} WHERE {
  {
    GRAPH <http://mu.semte.ch/application> {
      ?4dc8a089e387 a <http://data.lblod.info/ML2GrowClassification/c7776fbb-a32a-419c-b996-4dc8a089e387>.
    }
  } UNION {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?4dc8a089e387 a <http://data.lblod.info/ML2GrowClassification/c7776fbb-a32a-419c-b996-4dc8a089e387>.
    }
  }
  GRAPH <http://mu.semte.ch/application> {
    ?4dc8a089e387 ?4dc8a089e387P ?4dc8a089e387O.
  }
}